## Numpy Introduction
---

### 1. Numpy Array and Matrix:

In [16]:
import numpy as np

arr = [1, 2, 3, 4, 5, 6]

# Create a numpy array of type float32
a = np.array(arr, dtype=np.float32)

a

array([ 1.,  2.,  3.,  4.,  5.,  6.], dtype=float32)

In [17]:
mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create a numpy matrix of type int64(default)
m = np.matrix(mat)

m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
# Length of numpy object in each direction
print a.shape
print m.shape

(6,)
(3, 3)


In [19]:
# Find the index with the largest value
np.argmax(a)

5

In [41]:
# Reshaping an existing numpy array
print a.reshape((3, 2))
print '\n'
print np.reshape(a = a, newshape = (2, 3))

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [42]:
# Flatten and transpose the matrix 'm'
m.flatten().T

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

### 2. Numpy Random Numbers and Common in-built functions

In [67]:
# Generate random integers between [0, 10) 
np.random.randint(low = 0, high = 10, size = (3, 3))

array([[8, 0, 5],
       [0, 9, 6],
       [2, 0, 5]])

In [68]:
# Set the seed so that all random numbers are generated from same distribution
np.random.seed(1234)

In [69]:
# Generate random numbers from a uniform distributions
np.random.uniform(low = -np.sqrt(1./10), high = np.sqrt(1./10), size = 10)

array([-0.19510023,  0.07722837, -0.03938444,  0.18047661,  0.17707225,
       -0.14382506, -0.14137642,  0.19092073,  0.28975277,  0.23776067])

In [62]:
# Generate some zeros
np.zeros(shape = 10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [63]:
# Generate some ones
np.ones(shape = 10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
np.sum(m)

45

In [70]:
# Generate a diagonal matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### 3. Vectorization

In [71]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
b = np.arange(10000)

%timeit b + 10

The slowest run took 14.22 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.22 µs per loop


In [90]:
c = range(10000)

%timeit [x + 10 for x in c]

The slowest run took 4.37 times longer than the fastest. This could mean that an intermediate result is being cached 
1000 loops, best of 3: 349 µs per loop


In [97]:
a = np.arange(10000)
b = np.ones(10000)

(a + b)[:10]

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [106]:
# Vectorized dot product
np.dot(np.random.randint(1, 100, (100, 100)), np.eye(100))

array([[ 59.,  10.,  70., ...,  18.,  92.,  96.],
       [ 33.,  85.,  79., ...,  40.,  86.,   2.],
       [ 30.,   7.,   7., ...,  66.,  54.,  64.],
       ..., 
       [ 57.,  38.,  65., ...,  29.,  81.,  69.],
       [ 80.,   3.,  97., ...,  16.,  58.,  37.],
       [ 67.,  30.,  52., ...,  82.,  30.,  25.]])